name: google_mobile_ads_unity
description: Google Mobile Ads mediation plugin for Unity Ads.
version: 3.2.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.androidhuman.plugins.google_mobile_ads_unity
        pluginClass: GoogleMobileAdsUnityPlugin
      ios:
        pluginClass: AHMGoogleMobileAdsUnityPlugin
